apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-feed-deployment-blue
  namespace: researchfeed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-feed-deployment-blue
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30