apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-feed-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-feed-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10