apiVersion: v1
kind: Service
metadata:
  name: my-feed-ui-service
  namespace: researchfeed
spec:
  type: LoadBalancer
  selector:
    app: my-feed-ui
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http