apiVersion: v1
kind: Service
metadata:
  name: my-feed-service-stage
  namespace: researchfeed
spec:
  type: LoadBalancer
  selector:
    app: my-feed
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http