apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-feed-ui-deployment-blue
  namespace: researchfeed
  labels:
    app: my-feed-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-feed-ui
      version: blue
  template:
    metadata:
      labels:
        app: my-feed-ui
        version: blue
    spec:
      containers:
        - name: my-feed-ui
          image: researchportal/rp-cloud-ui:v1
          ports:
            - containerPort: 4200