apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-feed-deployment-green
  namespace: researchfeed
  labels:
    app: my-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-feed
      version: green
  template:
    metadata:
      annotation:
        prometheus.io/scraps: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "8000"
      labels:
        app: my-feed
        version: green
    spec:
      containers:
        - name: my-feed
          image: researchportal/rp-cloud:v3Green
          ports:
            - containerPort: 8000
            - containerPort: 80
          resources:
            requests:
              cpu: 30m
          livenessProbe:
            httpGet:
              path: /statusservice/status
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1