apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-feed-deployment-blue
  namespace: researchfeed
  labels:
    app: my-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-feed
      version: blue
  template:
    metadata:
      labels:
        app: my-feed
        version: blue
    spec:
      containers:
        - name: my-feed
          image: researchportal/rp-cloud:v15
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 30m
          livenessProbe:
            httpGet:
              path: /statusservice/status
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1